### ISSUE TITLE
NameError: undefined local variable or method `username' for #<Handler:0x00000004138040>

### ISSUE THREAD

**Issue by bernardobarreto** [OmG3r/steam-trade#3]
Hello,
I was trying to login with steam-trade but I received the following error:

```2.3.1 :008 >   a = Handler.new('xxxxxx', 'xxxxxx', 'xxxxxxx')
25-07-2018 18:51:58 ::  :: Handler started
NameError: undefined local variable or method `username' for #<Handler:0x00000004138040>
Did you mean?  @username
        from (irb):8:in `new'
        from (irb):8
```

Any thoughts on this?
ps: the original credentials were replaced by `xxxx` in the example above.

Also, I'm located in Brazil, what number should I pass as time_difference?

Thanks in advance.

**Comment by OmG3r** [comment]
can you please write the code you used ?
and ruby version too

**Comment by bernardobarreto** [comment]
@OmG3r I actually managed to work. Thanks
